make1:
	g++-10 Dungeon.cpp Creature.cpp Alive_Creature.cpp Dead_Creature.cpp Summoner.cpp Golem.cpp User.cpp -std=c++20 -Wall -Wextra -g
make2:
	g++-10 User.cpp Golem.cpp Summoner.cpp Dead_Creature.cpp Alive_Creature.cpp Creature.cpp Dungeon.cpp -std=c++20 -Wall -Wextra -g