make:
	g++-10 -std=c++20 Alive_Creature.cpp Creature.cpp Dead_Creature.cpp Dungeon.cpp Golem.cpp main.cpp Summoner.cpp User.cpp -Wall -Wextra -g
all_in_one:
	g++-10 -std=c++20 ALL_IN_ONE.cpp main.cpp Summoner.cpp Golem.cpp -Wextra -Wall -g
ALL_IN_ONE:
	g++-10 -std=c++20 ALL_IN_ONE.cpp main.cpp -Wall -Wextra -g -D ALL_IN_ONE_TRUE